name: Build & Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: pudim-bakery

      - name: Lint
        run: npx next lint || true
        working-directory: pudim-bakery

      - name: Type Check
        run: npx tsc --noEmit
        working-directory: pudim-bakery

      - name: Build
        run: npm run build
        working-directory: pudim-bakery